/**
 * Registry of all blog posts. Same URLs as old Wix (/post/[slug]) for SEO.
 * Generated by scripts/scrape-wix-blogs.mjs
 */
import type { BlogPost } from "@/types/content";
import p_advantages_edof_iol_mumbai from "./advantages-edof-iol-mumbai";
import p_advantages_of_edof_iol_over_multifocal from "./advantages-of-edof-iol-over-multifocal";
import p_aesthetic_ophthalmology_mumbai_guide from "./aesthetic-ophthalmology-mumbai-guide";
import p_are_eye_floaters_normal_after_40 from "./are-eye-floaters-normal-after-40";
import p_benefits_of_phaco_cataract_surgery from "./benefits-of-phaco-cataract-surgery";
import p_best_eye_drops_for_dry_eyes from "./best-eye-drops-for-dry-eyes";
import p_best_fruits_for_eyes from "./best-fruits-for-eyes";
import p_best_fruits_for_eyesight_improvement_natural_vision_boosters from "./best-fruits-for-eyesight-improvement-natural-vision-boosters";
import p_best_glaucoma_treatment_in_mumbai_early_detection_specialists_laser_surgery_options from "./best-glaucoma-treatment-in-mumbai-early-detection-specialists-laser-surgery-options";
import p_best_lasik_laser_eye_surgery_in_mumbai_how_to_choose_the_right_doctor from "./best-lasik-laser-eye-surgery-in-mumbai-how-to-choose-the-right-doctor";
import p_blepharoplasty_eyelid_surgery_mumbai from "./blepharoplasty-eyelid-surgery-mumbai";
import p_can_cataract_come_back_after_surgery from "./can-cataract-come-back-after-surgery";
import p_can_dry_eye_cause_blurry_vision_permanently from "./can-dry-eye-cause-blurry-vision-permanently";
import p_can_glaucoma_exist_without_symptoms from "./can-glaucoma-exist-without-symptoms";
import p_cataract_surgery_cost_india_vs_usa_uk_uae from "./cataract-surgery-cost-india-vs-usa-uk-uae";
import p_cataract_surgery_cost_mumbai from "./cataract-surgery-cost-mumbai";
import p_cataract_surgery_mumbai from "./cataract-surgery-mumbai";
import p_cataract_surgery_mumbai_guide from "./cataract-surgery-mumbai-guide";
import p_cataract_surgery_recovery_time_healing_aftercare_what_to_expect from "./cataract-surgery-recovery-time-healing-aftercare-what-to-expect";
import p_common_eye_area_aesthetic_concerns_solutions from "./common-eye-area-aesthetic-concerns-solutions";
import p_contoura_vision_mumbai_bandra_guide from "./contoura-vision-mumbai-bandra-guide";
import p_digital_eye_strain_how_to_protect_your_vision_in_the_screen_age from "./digital-eye-strain-how-to-protect-your-vision-in-the-screen-age";
import p_do_edof_lenses_cause_halos_or_glare from "./do-edof-lenses-cause-halos-or-glare";
import p_dry_eye_disease_treatment_mumbai from "./dry-eye-disease-treatment-mumbai";
import p_dry_eye_home_treatment from "./dry-eye-home-treatment";
import p_dry_eye_therapy_mumbai from "./dry-eye-therapy-mumbai";
import p_dry_eye_treatment_in_mumbai_causes_modern_treatments_long_term_relief from "./dry-eye-treatment-in-mumbai-causes-modern-treatments-long-term-relief";
import p_dry_eye_treatment_mumbai_guide from "./dry-eye-treatment-mumbai-guide";
import p_edof_iol_surgery_mumbai_guide from "./edof-iol-surgery-mumbai-guide";
import p_edof_iol_vs_trifocal_iol from "./edof-iol-vs-trifocal-iol";
import p_edof_lens_night_driving_mumbai from "./edof-lens-night-driving-mumbai";
import p_everything_you_need_to_know_about_robotic_cataract_surgery_in_mumbai from "./everything-you-need-to-know-about-robotic-cataract-surgery-in-mumbai";
import p_eye_treatment_mumbai_international_patients from "./eye-treatment-mumbai-international-patients";
import p_glaucoma_the_silent_thief_of_sight_and_how_to_catch_it_early from "./glaucoma-the-silent-thief-of-sight-and-how-to-catch-it-early";
import p_how_often_should_child_eye_checkup from "./how-often-should-child-eye-checkup";
import p_icl_surgery_mumbai_india_guide from "./icl-surgery-mumbai-india-guide";
import p_ideal_candidate_for_phaco_cataract_surgery from "./ideal-candidate-for-phaco-cataract-surgery";
import p_ipl_and_morpheus_for_dry_eye_treatment_restoring_comfort_and_clarity_at_i_sight_eye_care_mumbai from "./ipl-and-morpheus-for-dry-eye-treatment-restoring-comfort-and-clarity-at-i-sight-eye-care-mumbai";
import p_ipl_treatment_dry_eye_mumbai_guide from "./ipl-treatment-dry-eye-mumbai-guide";
import p_is_dry_eye_dangerous from "./is-dry-eye-dangerous";
import p_is_eye_surgery_in_india_safe_for_international_patients from "./is-eye-surgery-in-india-safe-for-international-patients";
import p_is_lasik_safe_after_40 from "./is-lasik-safe-after-40";
import p_is_phaco_cataract_surgery_safe_for_elderly from "./is-phaco-cataract-surgery-safe-for-elderly";
import p_laser_treatment_for_eyes_in_mumbai_who_it_s_for_how_it_works_and_what_to_expect from "./laser-treatment-for-eyes-in-mumbai-who-it-s-for-how-it-works-and-what-to-expect";
import p_lasik_in_khar_mumbai from "./lasik-in-khar-mumbai";
import p_lasik_surgery_bandra_mumbai_guide from "./lasik-surgery-bandra-mumbai-guide";
import p_morpheus_eye_rejuvenation_brighten_and_tighten_the_eyes_naturally from "./morpheus-eye-rejuvenation-brighten-and-tighten-the-eyes-naturally";
import p_myopia_treatment_mumbai_guide from "./myopia-treatment-mumbai-guide";
import p_myths_about_phaco_cataract_surgery from "./myths-about-phaco-cataract-surgery";
import p_ophthalmic_aesthetics_mumbai_guide from "./ophthalmic-aesthetics-mumbai-guide";
import p_pediatric_eye_care_mumbai_in_mumbai_conditions_treatments_why_early_checks_matter from "./pediatric-eye-care-mumbai-in-mumbai-conditions-treatments-why-early-checks-matter";
import p_pediatric_eye_care_mumbai_in_mumbai_early_eye_checks_big_vision_for_little_eyes from "./pediatric-eye-care-mumbai-in-mumbai-early-eye-checks-big-vision-for-little-eyes";
import p_pediatric_eye_doctor from "./pediatric-eye-doctor";
import p_pediatric_eye_doctor_india from "./pediatric-eye-doctor-india";
import p_pediatric_eye_doctor_near_me from "./pediatric-eye-doctor-near-me";
import p_phaco_mumbai from "./phaco-mumbai";
import p_phaco_surgery_mumbai from "./phaco-surgery-mumbai";
import p_phaco_surgery_recovery_timeline from "./phaco-surgery-recovery-timeline";
import p_phaco_vs_traditional_cataract_surgery from "./phaco-vs-traditional-cataract-surgery";
import p_phaco_vs_traditional_cataract_surgery_which_technique_gives_better_results_in_mumbai from "./phaco-vs-traditional-cataract-surgery-which-technique-gives-better-results-in-mumbai";
import p_the_complete_guide_to_kids_eye_check_ups_when_why_and_how_to_protect_young_vision from "./the-complete-guide-to-kids-eye-check-ups-when-why-and-how-to-protect-young-vision";
import p_top_lasik_clinics_in_bandra from "./top-lasik-clinics-in-bandra";
import p_top_rated_lasik_surgeons_in_bandra from "./top-rated-lasik-surgeons-in-bandra";
import p_unlocking_clarity_understanding_the_cornea_of_the_eye_and_its_vital_role_in_vision from "./unlocking-clarity-understanding-the-cornea-of-the-eye-and-its-vital-role-in-vision";
import p_vision_20_20_what_it_really_means_and_how_to_achieve_it_in_mumbai from "./vision-20-20-what-it-really-means-and-how-to-achieve-it-in-mumbai";
import p_what_age_should_cataract_surgery_be_done from "./what-age-should-cataract-surgery-be-done";
import p_when_floaters_mean_trouble_understanding_retina_health from "./when-floaters-mean-trouble-understanding-retina-health";
import p_which_fruits_good_for_eyesight from "./which-fruits-good-for-eyesight";
import p_who_should_perform_eye_aesthetic_treatments from "./who-should-perform-eye-aesthetic-treatments";
import p_why_dry_eye_occurs from "./why-dry-eye-occurs";
import p_why_icl_instead_of_lasik from "./why-icl-instead-of-lasik";
import p_lasik_laser_eye_surgery_cost_in_india from "./lasik-laser-eye-surgery-cost-in-india";
import p_does_lasik_permanently_fix_eyes from "./does-lasik-permanently-fix-eyes";
import p_how_does_lasik_surgery_work_process_and_recovery from "./how-does-lasik-surgery-work-process-and-recovery";
import p_best_clinics_for_lasik_eye_surgery_in_india from "./best-clinics-for-lasik-eye-surgery-in-india";
import p_advanced_eye_surgery_latest_technology_near_me from "./advanced-eye-surgery-latest-technology-near-me";
import p_best_eye_hospitals_laser_vision_correction_india from "./best-eye-hospitals-laser-vision-correction-india";
import p_affordable_advanced_eye_surgery_packages_india from "./affordable-advanced-eye-surgery-packages-india";
import p_customized_cataract_surgery_options_india from "./customized-cataract-surgery-options-india";
import p_eye_surgery_centers_financing_emi_plans_india from "./eye-surgery-centers-financing-emi-plans-india";
import p_consultation_premium_lens_implant_surgeries_india from "./consultation-premium-lens-implant-surgeries-india";
import p_hospitals_using_bladeless_laser_eye_surgery_india from "./hospitals-using-bladeless-laser-eye-surgery-india";
import p_advanced_eye_surgery_insurance_coverage_india from "./advanced-eye-surgery-insurance-coverage-india";
import p_patient_reviews_advanced_eye_surgery_centers from "./patient-reviews-advanced-eye-surgery-centers";
import p_experienced_retinal_surgery_clinics_india from "./experienced-retinal-surgery-clinics-india";
import p_top_rated_corneal_transplant_centers_india from "./top-rated-corneal-transplant-centers-india";
import p_advanced_glaucoma_surgery_minimal_downtime_india from "./advanced-glaucoma-surgery-minimal-downtime-india";
import p_hospitals_for_pediatric_advanced_eye_surgeries_india from "./hospitals-for-pediatric-advanced-eye-surgeries-india";
import p_same_day_advanced_eye_surgery_procedures_india from "./same-day-advanced-eye-surgery-procedures-india";
import p_advanced_refractive_surgery_quick_recovery_centers_india from "./advanced-refractive-surgery-quick-recovery-centers-india";

import p_what_is_lasik_eye_surgery_and_how_it_works from "./what-is-lasik-eye-surgery-and-how-it-works";
import p_is_lasik_safe_risks_side_effects_and_expectations from "./is-lasik-safe-risks-side-effects-and-expectations";
import p_lasik_cost_in_mumbai_packages_emi_and_pricing_factors from "./lasik-cost-in-mumbai-packages-emi-and-pricing-factors";
import p_lasik_recovery_timeline_work_drive_gym_travel from "./lasik-recovery-timeline-work-drive-gym-travel";
import p_who_is_a_good_candidate_for_lasik_eligibility_tests from "./who-is-a-good-candidate-for-lasik-eligibility-tests";
import p_lasik_for_high_power_thin_cornea_high_myopia from "./lasik-for-high-power-thin-cornea-high-myopia";
import p_lasik_after_40_vs_lens_based_vision_correction from "./lasik-after-40-vs-lens-based-vision-correction";
import p_lasik_vs_smile_vs_prk_which_is_best from "./lasik-vs-smile-vs-prk-which-is-best";
import p_bladeless_lasik_explained_benefits_and_limitations from "./bladeless-lasik-explained-benefits-and-limitations";
import p_lasik_success_rate_long_term_results_and_enhancements from "./lasik-success-rate-long-term-results-and-enhancements";
import p_lasik_for_astigmatism_can_cylindrical_power_be_corrected from "./lasik-for-astigmatism-can-cylindrical-power-be-corrected";
import p_can_lasik_treat_myopia_and_hyperopia from "./can-lasik-treat-myopia-and-hyperopia";
import p_lasik_and_dry_eye_can_you_still_undergo_surgery from "./lasik-and-dry-eye-can-you-still-undergo-surgery";
import p_does_lasik_hurt_pain_anesthesia_and_comfort_guide from "./does-lasik-hurt-pain-anesthesia-and-comfort-guide";
import p_lasik_consultation_checklist_questions_to_ask_surgeon from "./lasik-consultation-checklist-questions-to-ask-surgeon";
import p_best_lasik_surgeon_in_mumbai_how_to_choose from "./best-lasik-surgeon-in-mumbai-how-to-choose";
import p_best_lasik_clinic_in_bandra_and_mumbai_selection_guide from "./best-lasik-clinic-in-bandra-and-mumbai-selection-guide";
import p_lasik_vs_icl_when_lens_based_correction_is_better from "./lasik-vs-icl-when-lens-based-correction-is-better";
import p_free_lasik_eye_test_and_second_opinion_guide from "./free-lasik-eye-test-and-second-opinion-guide";
import p_lasik_faq_most_asked_questions_answered from "./lasik-faq-most-asked-questions-answered";
import p_best_lasik_surgeon_mumbai from "./best-lasik-surgeon-mumbai";
import p_is_lasik_safe_india_faq from "./is-lasik-safe-india-faq";
import p_lasik_eye_surgery_experience_mumbai from "./lasik-eye-surgery-experience-mumbai";
import p_lasik_eye_surgery_navi_mumbai from "./lasik-eye-surgery-navi-mumbai";
import p_lasik_eye_surgery_cost_mumbai from "./lasik-eye-surgery-cost-mumbai";
import p_lasik_eye_surgery_in_mumbai from "./lasik-eye-surgery-in-mumbai";
import p_lasik_hospital_mumbai from "./lasik-hospital-mumbai";
import p_lasik_navi_mumbai from "./lasik-navi-mumbai";
import p_lasik_operation_mumbai from "./lasik-operation-mumbai";
import p_lasik_surgery_cost_mumbai_reddit from "./lasik-surgery-cost-mumbai-reddit";
import p_best_lasik_surgery_mumbai from "./best-lasik-surgery-mumbai";
import p_how_much_does_lasik_eye_surgery_cost_india from "./how-much-does-lasik-eye-surgery-cost-india";
import p_what_is_lasik_eye_surgery_cost_india from "./what-is-lasik-eye-surgery-cost-india";
import p_how_much_does_lasik_cost_mumbai from "./how-much-does-lasik-cost-mumbai";
import p_contoura_vision_lasik_mumbai from "./contoura-vision-lasik-mumbai";
import p_smile_lasik_surgery_mumbai from "./smile-lasik-surgery-mumbai";
import p_silk_lasik_mumbai from "./silk-lasik-mumbai";
import p_femto_lasik_mumbai from "./femto-lasik-mumbai";
import p_lasik_surgery_cost_mumbai from "./lasik-surgery-cost-mumbai";
import p_lasik_vs_smile_vs_silk_vs_contoura_mumbai from "./lasik-vs-smile-vs-silk-vs-contoura-mumbai";
import p_best_cataract_surgeon_mumbai from "./best-cataract-surgeon-mumbai";
import p_cataract_surgery_navi_mumbai from "./cataract-surgery-navi-mumbai";
import p_dry_eye_specialist_mumbai from "./dry-eye-specialist-mumbai";
import p_eye_clinics_mumbai from "./eye-clinics-mumbai";
import p_eye_doctor_in_mumbai from "./eye-doctor-in-mumbai";
import p_eye_specialist_navi_mumbai from "./eye-specialist-navi-mumbai";
import p_icl_surgery_cost_mumbai from "./icl-surgery-cost-mumbai";
import p_laser_eye_surgery_mumbai_cost from "./laser-eye-surgery-mumbai-cost";
import p_premium_iol_lens_cost_mumbai_2026 from "./premium-iol-lens-cost-mumbai-2026";
import p_squint_eye_surgery_mumbai_cost from "./squint-eye-surgery-mumbai-cost";
import p_can_lasik_be_repeated_enhancement from "./can-lasik-be-repeated-enhancement";
import p_cataract_surgery_cost_mumbai_lenses from "./cataract-surgery-cost-mumbai-lenses";
import p_cataract_surgery_diabetes_safety from "./cataract-surgery-diabetes-safety";
import p_cataract_surgery_recovery_dos_donts from "./cataract-surgery-recovery-dos-donts";
import p_contoura_vision_cost_mumbai_worth_it from "./contoura-vision-cost-mumbai-worth-it";
import p_contoura_vision_recovery_return_work from "./contoura-vision-recovery-return-work";
import p_contoura_vision_side_effects from "./contoura-vision-side-effects";
import p_contoura_vision_vs_smile from "./contoura-vision-vs-smile";
import p_flacs_vs_phaco_cataract_surgery from "./flacs-vs-phaco-cataract-surgery";
import p_ideal_candidate_contoura_vision from "./ideal-candidate-contoura-vision";
import p_is_lasik_eye_surgery_painful_mumbai from "./is-lasik-eye-surgery-painful-mumbai";
import p_lasik_candidate_age_eligibility from "./lasik-candidate-age-eligibility";
import p_lasik_recovery_time_day_by_day_mumbai from "./lasik-recovery-time-day-by-day-mumbai";
import p_lasik_risks_side_effects from "./lasik-risks-side-effects";
import p_lasik_vs_contact_lenses_mumbai from "./lasik-vs-contact-lenses-mumbai";
import p_monofocal_vs_multifocal_iol from "./monofocal-vs-multifocal-iol";
import p_secondary_cataract_pco_after_surgery from "./secondary-cataract-pco-after-surgery";
import p_what_is_contoura_vision_vs_lasik from "./what-is-contoura-vision-vs-lasik";
import p_when_to_have_cataract_surgery from "./when-to-have-cataract-surgery";
import p_eye_specialist_doctor_mumbai from "./eye-specialist-doctor-mumbai";
import p_eye_doctor_mumbai from "./eye-doctor-mumbai";
import p_ophthalmologist_vs_optometrist_mumbai from "./ophthalmologist-vs-optometrist-mumbai";
import p_signs_see_eye_specialist_mumbai from "./signs-see-eye-specialist-mumbai";
import p_best_lasik_surgery_mumbai_procedure from "./best-lasik-surgery-mumbai-procedure";
import p_best_eye_hospital_mumbai_lasik from "./best-eye-hospital-mumbai-lasik";
import p_aesthetic_ophthalmology_mumbai from "./aesthetic-ophthalmology-mumbai";
import p_aesthetic_eye_rejuvenation_mumbai from "./aesthetic-eye-rejuvenation-mumbai";
import p_affordable_lasik_surgery_near_me_india from "./affordable-lasik-surgery-near-me-india";
import p_hospitals_advanced_lasik_technology_india from "./hospitals-advanced-lasik-technology-india";
import p_is_lasik_covered_by_insurance_india from "./is-lasik-covered-by-insurance-india";
import p_laser_eye_surgery_cost_major_indian_cities from "./laser-eye-surgery-cost-major-indian-cities";
import p_laser_eye_surgery_reviews_mumbai from "./laser-eye-surgery-reviews-mumbai";
import p_lasik_financing_emi_options_india from "./lasik-financing-emi-options-india";
import p_lasik_surgery_reviews_bangalore from "./lasik-surgery-reviews-bangalore";
import p_refractive_surgery_eligibility_criteria_india from "./refractive-surgery-eligibility-criteria-india";
import p_top_eye_clinics_vision_correction_delhi from "./top-eye-clinics-vision-correction-delhi";
import p_top_rated_lasik_surgeons_mumbai from "./top-rated-lasik-surgeons-mumbai";

const POSTS: Record<string, BlogPost> = {
  "advantages-edof-iol-mumbai": p_advantages_edof_iol_mumbai,
  "advantages-of-edof-iol-over-multifocal": p_advantages_of_edof_iol_over_multifocal,
  "aesthetic-ophthalmology-mumbai-guide": p_aesthetic_ophthalmology_mumbai_guide,
  "are-eye-floaters-normal-after-40": p_are_eye_floaters_normal_after_40,
  "benefits-of-phaco-cataract-surgery": p_benefits_of_phaco_cataract_surgery,
  "best-eye-drops-for-dry-eyes": p_best_eye_drops_for_dry_eyes,
  "best-fruits-for-eyes": p_best_fruits_for_eyes,
  "best-fruits-for-eyesight-improvement-natural-vision-boosters": p_best_fruits_for_eyesight_improvement_natural_vision_boosters,
  "best-glaucoma-treatment-in-mumbai-early-detection-specialists-laser-surgery-options": p_best_glaucoma_treatment_in_mumbai_early_detection_specialists_laser_surgery_options,
  "best-lasik-laser-eye-surgery-in-mumbai-how-to-choose-the-right-doctor": p_best_lasik_laser_eye_surgery_in_mumbai_how_to_choose_the_right_doctor,
  "blepharoplasty-eyelid-surgery-mumbai": p_blepharoplasty_eyelid_surgery_mumbai,
  "can-cataract-come-back-after-surgery": p_can_cataract_come_back_after_surgery,
  "can-dry-eye-cause-blurry-vision-permanently": p_can_dry_eye_cause_blurry_vision_permanently,
  "can-glaucoma-exist-without-symptoms": p_can_glaucoma_exist_without_symptoms,
  "can-lasik-be-repeated-enhancement": p_can_lasik_be_repeated_enhancement,
  "cataract-surgery-cost-india-vs-usa-uk-uae": p_cataract_surgery_cost_india_vs_usa_uk_uae,
  "cataract-surgery-cost-mumbai": p_cataract_surgery_cost_mumbai,
  "cataract-surgery-cost-mumbai-lenses": p_cataract_surgery_cost_mumbai_lenses,
  "cataract-surgery-diabetes-safety": p_cataract_surgery_diabetes_safety,
  "cataract-surgery-mumbai": p_cataract_surgery_mumbai,
  "cataract-surgery-mumbai-guide": p_cataract_surgery_mumbai_guide,
  "cataract-surgery-navi-mumbai": p_cataract_surgery_navi_mumbai,
  "cataract-surgery-recovery-dos-donts": p_cataract_surgery_recovery_dos_donts,
  "cataract-surgery-recovery-time-healing-aftercare-what-to-expect": p_cataract_surgery_recovery_time_healing_aftercare_what_to_expect,
  "common-eye-area-aesthetic-concerns-solutions": p_common_eye_area_aesthetic_concerns_solutions,
  "contoura-vision-cost-mumbai-worth-it": p_contoura_vision_cost_mumbai_worth_it,
  "contoura-vision-lasik-mumbai": p_contoura_vision_lasik_mumbai,
  "contoura-vision-mumbai-bandra-guide": p_contoura_vision_mumbai_bandra_guide,
  "contoura-vision-recovery-return-work": p_contoura_vision_recovery_return_work,
  "contoura-vision-side-effects": p_contoura_vision_side_effects,
  "contoura-vision-vs-smile": p_contoura_vision_vs_smile,
  "digital-eye-strain-how-to-protect-your-vision-in-the-screen-age": p_digital_eye_strain_how_to_protect_your_vision_in_the_screen_age,
  "do-edof-lenses-cause-halos-or-glare": p_do_edof_lenses_cause_halos_or_glare,
  "dry-eye-disease-treatment-mumbai": p_dry_eye_disease_treatment_mumbai,
  "dry-eye-home-treatment": p_dry_eye_home_treatment,
  "dry-eye-therapy-mumbai": p_dry_eye_therapy_mumbai,
  "dry-eye-treatment-in-mumbai-causes-modern-treatments-long-term-relief": p_dry_eye_treatment_in_mumbai_causes_modern_treatments_long_term_relief,
  "dry-eye-treatment-mumbai-guide": p_dry_eye_treatment_mumbai_guide,
  "dry-eye-specialist-mumbai": p_dry_eye_specialist_mumbai,
  "edof-iol-surgery-mumbai-guide": p_edof_iol_surgery_mumbai_guide,
  "edof-iol-vs-trifocal-iol": p_edof_iol_vs_trifocal_iol,
  "edof-lens-night-driving-mumbai": p_edof_lens_night_driving_mumbai,
  "everything-you-need-to-know-about-robotic-cataract-surgery-in-mumbai": p_everything_you_need_to_know_about_robotic_cataract_surgery_in_mumbai,
  "eye-treatment-mumbai-international-patients": p_eye_treatment_mumbai_international_patients,
  "eye-clinics-mumbai": p_eye_clinics_mumbai,
  "eye-doctor-in-mumbai": p_eye_doctor_in_mumbai,
  "eye-specialist-navi-mumbai": p_eye_specialist_navi_mumbai,
  "glaucoma-the-silent-thief-of-sight-and-how-to-catch-it-early": p_glaucoma_the_silent_thief_of_sight_and_how_to_catch_it_early,
  "how-often-should-child-eye-checkup": p_how_often_should_child_eye_checkup,
  "icl-surgery-mumbai-india-guide": p_icl_surgery_mumbai_india_guide,
  "icl-surgery-cost-mumbai": p_icl_surgery_cost_mumbai,
  "ideal-candidate-for-phaco-cataract-surgery": p_ideal_candidate_for_phaco_cataract_surgery,
  "ideal-candidate-contoura-vision": p_ideal_candidate_contoura_vision,
  "ipl-and-morpheus-for-dry-eye-treatment-restoring-comfort-and-clarity-at-i-sight-eye-care-mumbai": p_ipl_and_morpheus_for_dry_eye_treatment_restoring_comfort_and_clarity_at_i_sight_eye_care_mumbai,
  "ipl-treatment-dry-eye-mumbai-guide": p_ipl_treatment_dry_eye_mumbai_guide,
  "is-dry-eye-dangerous": p_is_dry_eye_dangerous,
  "is-eye-surgery-in-india-safe-for-international-patients": p_is_eye_surgery_in_india_safe_for_international_patients,
  "is-lasik-eye-surgery-painful-mumbai": p_is_lasik_eye_surgery_painful_mumbai,
  "is-lasik-safe-after-40": p_is_lasik_safe_after_40,
  "is-phaco-cataract-surgery-safe-for-elderly": p_is_phaco_cataract_surgery_safe_for_elderly,
  "laser-treatment-for-eyes-in-mumbai-who-it-s-for-how-it-works-and-what-to-expect": p_laser_treatment_for_eyes_in_mumbai_who_it_s_for_how_it_works_and_what_to_expect,
  "lasik-candidate-age-eligibility": p_lasik_candidate_age_eligibility,
  "lasik-in-khar-mumbai": p_lasik_in_khar_mumbai,
  "lasik-surgery-bandra-mumbai-guide": p_lasik_surgery_bandra_mumbai_guide,
  "lasik-surgery-cost-mumbai": p_lasik_surgery_cost_mumbai,
  "monofocal-vs-multifocal-iol": p_monofocal_vs_multifocal_iol,
  "morpheus-eye-rejuvenation-brighten-and-tighten-the-eyes-naturally": p_morpheus_eye_rejuvenation_brighten_and_tighten_the_eyes_naturally,
  "myopia-treatment-mumbai-guide": p_myopia_treatment_mumbai_guide,
  "myths-about-phaco-cataract-surgery": p_myths_about_phaco_cataract_surgery,
  "ophthalmic-aesthetics-mumbai-guide": p_ophthalmic_aesthetics_mumbai_guide,
  "pediatric-eye-care-mumbai-in-mumbai-conditions-treatments-why-early-checks-matter": p_pediatric_eye_care_mumbai_in_mumbai_conditions_treatments_why_early_checks_matter,
  "pediatric-eye-care-mumbai-in-mumbai-early-eye-checks-big-vision-for-little-eyes": p_pediatric_eye_care_mumbai_in_mumbai_early_eye_checks_big_vision_for_little_eyes,
  "pediatric-eye-doctor": p_pediatric_eye_doctor,
  "pediatric-eye-doctor-india": p_pediatric_eye_doctor_india,
  "pediatric-eye-doctor-near-me": p_pediatric_eye_doctor_near_me,
  "phaco-mumbai": p_phaco_mumbai,
  "phaco-surgery-mumbai": p_phaco_surgery_mumbai,
  "phaco-surgery-recovery-timeline": p_phaco_surgery_recovery_timeline,
  "phaco-vs-traditional-cataract-surgery": p_phaco_vs_traditional_cataract_surgery,
  "phaco-vs-traditional-cataract-surgery-which-technique-gives-better-results-in-mumbai": p_phaco_vs_traditional_cataract_surgery_which_technique_gives_better_results_in_mumbai,
  "premium-iol-lens-cost-mumbai-2026": p_premium_iol_lens_cost_mumbai_2026,
  "the-complete-guide-to-kids-eye-check-ups-when-why-and-how-to-protect-young-vision": p_the_complete_guide_to_kids_eye_check_ups_when_why_and_how_to_protect_young_vision,
  "top-lasik-clinics-in-bandra": p_top_lasik_clinics_in_bandra,
  "top-rated-lasik-surgeons-in-bandra": p_top_rated_lasik_surgeons_in_bandra,
  "unlocking-clarity-understanding-the-cornea-of-the-eye-and-its-vital-role-in-vision": p_unlocking_clarity_understanding_the_cornea_of_the_eye_and_its_vital_role_in_vision,
  "vision-20-20-what-it-really-means-and-how-to-achieve-it-in-mumbai": p_vision_20_20_what_it_really_means_and_how_to_achieve_it_in_mumbai,
  "what-age-should-cataract-surgery-be-done": p_what_age_should_cataract_surgery_be_done,
  "when-to-have-cataract-surgery": p_when_to_have_cataract_surgery,
  "when-floaters-mean-trouble-understanding-retina-health": p_when_floaters_mean_trouble_understanding_retina_health,
  "which-fruits-good-for-eyesight": p_which_fruits_good_for_eyesight,
  "who-should-perform-eye-aesthetic-treatments": p_who_should_perform_eye_aesthetic_treatments,
  "why-dry-eye-occurs": p_why_dry_eye_occurs,
  "why-icl-instead-of-lasik": p_why_icl_instead_of_lasik,
  "lasik-laser-eye-surgery-cost-in-india": p_lasik_laser_eye_surgery_cost_in_india,
  "does-lasik-permanently-fix-eyes": p_does_lasik_permanently_fix_eyes,
  "how-does-lasik-surgery-work-process-and-recovery": p_how_does_lasik_surgery_work_process_and_recovery,
  "best-clinics-for-lasik-eye-surgery-in-india": p_best_clinics_for_lasik_eye_surgery_in_india,
  "advanced-eye-surgery-latest-technology-near-me": p_advanced_eye_surgery_latest_technology_near_me,
  "best-eye-hospitals-laser-vision-correction-india": p_best_eye_hospitals_laser_vision_correction_india,
  "affordable-advanced-eye-surgery-packages-india": p_affordable_advanced_eye_surgery_packages_india,
  "customized-cataract-surgery-options-india": p_customized_cataract_surgery_options_india,
  "eye-surgery-centers-financing-emi-plans-india": p_eye_surgery_centers_financing_emi_plans_india,
  "consultation-premium-lens-implant-surgeries-india": p_consultation_premium_lens_implant_surgeries_india,
  "hospitals-using-bladeless-laser-eye-surgery-india": p_hospitals_using_bladeless_laser_eye_surgery_india,
  "advanced-eye-surgery-insurance-coverage-india": p_advanced_eye_surgery_insurance_coverage_india,
  "patient-reviews-advanced-eye-surgery-centers": p_patient_reviews_advanced_eye_surgery_centers,
  "experienced-retinal-surgery-clinics-india": p_experienced_retinal_surgery_clinics_india,
  "top-rated-corneal-transplant-centers-india": p_top_rated_corneal_transplant_centers_india,
  "advanced-glaucoma-surgery-minimal-downtime-india": p_advanced_glaucoma_surgery_minimal_downtime_india,
  "hospitals-for-pediatric-advanced-eye-surgeries-india": p_hospitals_for_pediatric_advanced_eye_surgeries_india,
  "same-day-advanced-eye-surgery-procedures-india": p_same_day_advanced_eye_surgery_procedures_india,
  "secondary-cataract-pco-after-surgery": p_secondary_cataract_pco_after_surgery,
  "squint-eye-surgery-mumbai-cost": p_squint_eye_surgery_mumbai_cost,
  "advanced-refractive-surgery-quick-recovery-centers-india": p_advanced_refractive_surgery_quick_recovery_centers_india,
  "what-is-contoura-vision-vs-lasik": p_what_is_contoura_vision_vs_lasik,
  "what-is-lasik-eye-surgery-and-how-it-works": p_what_is_lasik_eye_surgery_and_how_it_works,
  "is-lasik-safe-risks-side-effects-and-expectations": p_is_lasik_safe_risks_side_effects_and_expectations,
  "is-lasik-safe-india-faq": p_is_lasik_safe_india_faq,
  "lasik-cost-in-mumbai-packages-emi-and-pricing-factors": p_lasik_cost_in_mumbai_packages_emi_and_pricing_factors,
  "laser-eye-surgery-mumbai-cost": p_laser_eye_surgery_mumbai_cost,
  "lasik-eye-surgery-experience-mumbai": p_lasik_eye_surgery_experience_mumbai,
  "lasik-eye-surgery-navi-mumbai": p_lasik_eye_surgery_navi_mumbai,
  "lasik-eye-surgery-cost-mumbai": p_lasik_eye_surgery_cost_mumbai,
  "lasik-eye-surgery-in-mumbai": p_lasik_eye_surgery_in_mumbai,
  "lasik-hospital-mumbai": p_lasik_hospital_mumbai,
  "lasik-navi-mumbai": p_lasik_navi_mumbai,
  "lasik-operation-mumbai": p_lasik_operation_mumbai,
  "lasik-recovery-time-day-by-day-mumbai": p_lasik_recovery_time_day_by_day_mumbai,
  "lasik-recovery-timeline-work-drive-gym-travel": p_lasik_recovery_timeline_work_drive_gym_travel,
  "lasik-risks-side-effects": p_lasik_risks_side_effects,
  "lasik-surgery-cost-mumbai-reddit": p_lasik_surgery_cost_mumbai_reddit,
  "best-lasik-surgery-mumbai": p_best_lasik_surgery_mumbai,
  "how-much-does-lasik-eye-surgery-cost-india": p_how_much_does_lasik_eye_surgery_cost_india,
  "what-is-lasik-eye-surgery-cost-india": p_what_is_lasik_eye_surgery_cost_india,
  "how-much-does-lasik-cost-mumbai": p_how_much_does_lasik_cost_mumbai,
  "smile-lasik-surgery-mumbai": p_smile_lasik_surgery_mumbai,
  "silk-lasik-mumbai": p_silk_lasik_mumbai,
  "femto-lasik-mumbai": p_femto_lasik_mumbai,
  "flacs-vs-phaco-cataract-surgery": p_flacs_vs_phaco_cataract_surgery,
  "who-is-a-good-candidate-for-lasik-eligibility-tests": p_who_is_a_good_candidate_for_lasik_eligibility_tests,
  "lasik-for-high-power-thin-cornea-high-myopia": p_lasik_for_high_power_thin_cornea_high_myopia,
  "lasik-after-40-vs-lens-based-vision-correction": p_lasik_after_40_vs_lens_based_vision_correction,
  "lasik-vs-smile-vs-prk-which-is-best": p_lasik_vs_smile_vs_prk_which_is_best,
  "lasik-vs-smile-vs-silk-vs-contoura-mumbai": p_lasik_vs_smile_vs_silk_vs_contoura_mumbai,
  "bladeless-lasik-explained-benefits-and-limitations": p_bladeless_lasik_explained_benefits_and_limitations,
  "lasik-success-rate-long-term-results-and-enhancements": p_lasik_success_rate_long_term_results_and_enhancements,
  "lasik-for-astigmatism-can-cylindrical-power-be-corrected": p_lasik_for_astigmatism_can_cylindrical_power_be_corrected,
  "can-lasik-treat-myopia-and-hyperopia": p_can_lasik_treat_myopia_and_hyperopia,
  "lasik-and-dry-eye-can-you-still-undergo-surgery": p_lasik_and_dry_eye_can_you_still_undergo_surgery,
  "does-lasik-hurt-pain-anesthesia-and-comfort-guide": p_does_lasik_hurt_pain_anesthesia_and_comfort_guide,
  "lasik-consultation-checklist-questions-to-ask-surgeon": p_lasik_consultation_checklist_questions_to_ask_surgeon,
  "best-lasik-surgeon-in-mumbai-how-to-choose": p_best_lasik_surgeon_in_mumbai_how_to_choose,
  "best-lasik-surgeon-mumbai": p_best_lasik_surgeon_mumbai,
  "best-cataract-surgeon-mumbai": p_best_cataract_surgeon_mumbai,
  "best-lasik-clinic-in-bandra-and-mumbai-selection-guide": p_best_lasik_clinic_in_bandra_and_mumbai_selection_guide,
  "lasik-vs-contact-lenses-mumbai": p_lasik_vs_contact_lenses_mumbai,
  "lasik-vs-icl-when-lens-based-correction-is-better": p_lasik_vs_icl_when_lens_based_correction_is_better,
  "free-lasik-eye-test-and-second-opinion-guide": p_free_lasik_eye_test_and_second_opinion_guide,
  "lasik-faq-most-asked-questions-answered": p_lasik_faq_most_asked_questions_answered,
  "eye-specialist-doctor-mumbai": p_eye_specialist_doctor_mumbai,
  "eye-doctor-mumbai": p_eye_doctor_mumbai,
  "ophthalmologist-vs-optometrist-mumbai": p_ophthalmologist_vs_optometrist_mumbai,
  "signs-see-eye-specialist-mumbai": p_signs_see_eye_specialist_mumbai,
  "best-lasik-surgery-mumbai-procedure": p_best_lasik_surgery_mumbai_procedure,
  "best-eye-hospital-mumbai-lasik": p_best_eye_hospital_mumbai_lasik,
  "aesthetic-ophthalmology-mumbai": p_aesthetic_ophthalmology_mumbai,
  "aesthetic-eye-rejuvenation-mumbai": p_aesthetic_eye_rejuvenation_mumbai,
  "affordable-lasik-surgery-near-me-india": p_affordable_lasik_surgery_near_me_india,
  "hospitals-advanced-lasik-technology-india": p_hospitals_advanced_lasik_technology_india,
  "is-lasik-covered-by-insurance-india": p_is_lasik_covered_by_insurance_india,
  "laser-eye-surgery-cost-major-indian-cities": p_laser_eye_surgery_cost_major_indian_cities,
  "laser-eye-surgery-reviews-mumbai": p_laser_eye_surgery_reviews_mumbai,
  "lasik-financing-emi-options-india": p_lasik_financing_emi_options_india,
  "lasik-surgery-reviews-bangalore": p_lasik_surgery_reviews_bangalore,
  "refractive-surgery-eligibility-criteria-india": p_refractive_surgery_eligibility_criteria_india,
  "top-eye-clinics-vision-correction-delhi": p_top_eye_clinics_vision_correction_delhi,
  "top-rated-lasik-surgeons-mumbai": p_top_rated_lasik_surgeons_mumbai,

};

export default POSTS;
